### ISSUE TITLE
return datetime.fromtimestamp(timestamp) :: bug

### ISSUE THREAD

**Issue by francesco1119** [stevenhgs/rib-to-gpx-file-converter#1]
Hi, I'm Francesco, the guy that you helped on StackOverflow. 

There is a bug around return `datetime.fromtimestamp(timestamp)` that I wasn't able to nail down. 

Basically the date is always the timestamp:

![compare scripts](https://user-images.githubusercontent.com/3397477/173350737-0cb303dd-b5ab-4388-9c22-2c06b24b09f2.png)

In the picture I'm comparing your script with [flight-converter](https://github.com/evilwombat/flight-converter)

**Comment by stevenhgs** [comment]
Hey, 

this was because the track points did not include data for the date. However, It seems like the first data slice contains this information. In the last [commit](https://github.com/stevenhgs/rib-to-gpx-file-converter/commit/e8c5e4a02d1d617c8053ef9b3561114a7b9c4723) I changed the code and now it should convert it to the date of when the activity took place.

Let me know if it works correctly now for your files.

**Comment by francesco1119** [comment]
🎵 Work, work, work, work, work, work🎵

Thank you so much

**Comment by francesco1119** [comment]
This issue is closed. 
I have wrote a post about it: 

https://www.jeeja.biz/2022/06/14/reverse-engineer-zeal-optics-transcend-gps/

Tell to your brother that he can render the GPX on a WordPress website and have his own dashboards.
